"""修改表结构

Revision ID: 1b5cbeadca07
Revises: 97be8226990d
Create Date: 2018-07-20 11:31:46.159094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b5cbeadca07'
down_revision = '97be8226990d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_mainshow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('brandname', sa.String(length=32), nullable=True),
    sa.Column('img1', sa.String(length=200), nullable=True),
    sa.Column('childcid1', sa.Integer(), nullable=True),
    sa.Column('productid1', sa.Integer(), nullable=True),
    sa.Column('longname1', sa.String(length=100), nullable=True),
    sa.Column('price1', sa.Integer(), nullable=True),
    sa.Column('marketprice1', sa.Integer(), nullable=True),
    sa.Column('img2', sa.String(length=200), nullable=True),
    sa.Column('childcid2', sa.Integer(), nullable=True),
    sa.Column('productid2', sa.Integer(), nullable=True),
    sa.Column('longname2', sa.String(length=100), nullable=True),
    sa.Column('price2', sa.Integer(), nullable=True),
    sa.Column('marketprice2', sa.Integer(), nullable=True),
    sa.Column('img3', sa.String(length=200), nullable=True),
    sa.Column('childcid3', sa.Integer(), nullable=True),
    sa.Column('productid3', sa.Integer(), nullable=True),
    sa.Column('longname3', sa.String(length=100), nullable=True),
    sa.Column('price3', sa.Integer(), nullable=True),
    sa.Column('marketprice3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('axf_foodtypes', sa.Column('childtypenames', sa.String(length=200), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('typeid', sa.Integer(), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('typename', sa.String(length=32), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('typesort', sa.Integer(), nullable=True))
    op.drop_column('axf_foodtypes', 'img1')
    op.drop_column('axf_foodtypes', 'productid2')
    op.drop_column('axf_foodtypes', 'longname1')
    op.drop_column('axf_foodtypes', 'longname2')
    op.drop_column('axf_foodtypes', 'price1')
    op.drop_column('axf_foodtypes', 'trackid')
    op.drop_column('axf_foodtypes', 'marketprice1')
    op.drop_column('axf_foodtypes', 'brandname')
    op.drop_column('axf_foodtypes', 'marketprice3')
    op.drop_column('axf_foodtypes', 'price3')
    op.drop_column('axf_foodtypes', 'productid1')
    op.drop_column('axf_foodtypes', 'productid3')
    op.drop_column('axf_foodtypes', 'img2')
    op.drop_column('axf_foodtypes', 'childcid2')
    op.drop_column('axf_foodtypes', 'price2')
    op.drop_column('axf_foodtypes', 'childcid3')
    op.drop_column('axf_foodtypes', 'categoryid')
    op.drop_column('axf_foodtypes', 'childcid1')
    op.drop_column('axf_foodtypes', 'img3')
    op.drop_column('axf_foodtypes', 'name')
    op.drop_column('axf_foodtypes', 'img')
    op.drop_column('axf_foodtypes', 'longname3')
    op.drop_column('axf_foodtypes', 'marketprice2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('axf_foodtypes', sa.Column('marketprice2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('longname3', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('img', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('img3', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('childcid1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('categoryid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('childcid3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('price2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('childcid2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('img2', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('productid3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('productid1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('price3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('marketprice3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('brandname', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('marketprice1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('trackid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('price1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('longname2', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('longname1', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('axf_foodtypes', sa.Column('productid2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('axf_foodtypes', sa.Column('img1', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('axf_foodtypes', 'typesort')
    op.drop_column('axf_foodtypes', 'typename')
    op.drop_column('axf_foodtypes', 'typeid')
    op.drop_column('axf_foodtypes', 'childtypenames')
    op.drop_table('axf_mainshow')
    # ### end Alembic commands ###
