"""修改goodd表

Revision ID: 669359f8d0bb
Revises: 1b5cbeadca07
Create Date: 2018-07-20 11:39:18.709206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669359f8d0bb'
down_revision = '1b5cbeadca07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('axf_goods', sa.Column('childcidname', sa.String(length=32), nullable=True))
    op.add_column('axf_goods', sa.Column('productimg', sa.String(length=200), nullable=True))
    op.add_column('axf_goods', sa.Column('productlongname', sa.String(length=200), nullable=True))
    op.add_column('axf_goods', sa.Column('productname', sa.String(length=100), nullable=True))
    op.add_column('axf_goods', sa.Column('specifics', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('axf_goods', 'specifics')
    op.drop_column('axf_goods', 'productname')
    op.drop_column('axf_goods', 'productlongname')
    op.drop_column('axf_goods', 'productimg')
    op.drop_column('axf_goods', 'childcidname')
    # ### end Alembic commands ###
