"""empty message

Revision ID: 97be8226990d
Revises: 
Create Date: 2018-07-20 11:23:19.060181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97be8226990d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axf_foodtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('brandname', sa.String(length=32), nullable=True),
    sa.Column('img1', sa.String(length=200), nullable=True),
    sa.Column('childcid1', sa.Integer(), nullable=True),
    sa.Column('productid1', sa.Integer(), nullable=True),
    sa.Column('longname1', sa.String(length=100), nullable=True),
    sa.Column('price1', sa.Integer(), nullable=True),
    sa.Column('marketprice1', sa.Integer(), nullable=True),
    sa.Column('img2', sa.String(length=200), nullable=True),
    sa.Column('childcid2', sa.Integer(), nullable=True),
    sa.Column('productid2', sa.Integer(), nullable=True),
    sa.Column('longname2', sa.String(length=100), nullable=True),
    sa.Column('price2', sa.Integer(), nullable=True),
    sa.Column('marketprice2', sa.Integer(), nullable=True),
    sa.Column('img3', sa.String(length=200), nullable=True),
    sa.Column('childcid3', sa.Integer(), nullable=True),
    sa.Column('productid3', sa.Integer(), nullable=True),
    sa.Column('longname3', sa.String(length=100), nullable=True),
    sa.Column('price3', sa.Integer(), nullable=True),
    sa.Column('marketprice3', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.Column('isxf', sa.Boolean(), nullable=True),
    sa.Column('pmdesc', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('marketprice', sa.Float(), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.Column('childcid', sa.Integer(), nullable=True),
    sa.Column('dealerid', sa.Integer(), nullable=True),
    sa.Column('storenums', sa.Integer(), nullable=True),
    sa.Column('productnum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_mustbuy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('axf_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_name', sa.String(length=16), nullable=True),
    sa.Column('u_password', sa.String(length=128), nullable=True),
    sa.Column('u_email', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('u_icon', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('u_email'),
    sa.UniqueConstraint('u_name')
    )
    op.create_table('axf_wheel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('trackid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('vip_type', sa.Integer(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=8), nullable=True),
    sa.Column('business_modile', sa.String(length=16), nullable=True),
    sa.Column('qq', sa.String(length=16), nullable=True),
    sa.Column('backend_modile', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('business_phone', sa.String(length=16), nullable=True),
    sa.Column('backend_phone', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_domain'), 'merchant', ['domain'], unique=False)
    op.create_index(op.f('ix_merchant_name'), 'merchant', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_name'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_domain'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_table('userinfo')
    op.drop_table('axf_wheel')
    op.drop_table('axf_user')
    op.drop_table('axf_shop')
    op.drop_table('axf_nav')
    op.drop_table('axf_mustbuy')
    op.drop_table('axf_goods')
    op.drop_table('axf_foodtypes')
    # ### end Alembic commands ###
